### ISSUE TITLE
error shortly after it runs 

### ISSUE THREAD

**Issue by leodesigndev** [ajbogh/nMotion#42]
Error: ENOENT: no such file or directory, open 'C:\apps\camera_apps\leodesign\leocam4\recordings\leo_tap0_001\2021\6\6\2021-06-06T07:31:53.394Z.webm'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:361:12
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\apps\\camera_apps\\leodesign\\leocam4\\recordings\\leo_tap0_001\\2021\\6\\6\\2021-06-06T07:31:53.394Z.webm'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nmotion@1.1.0 server: `node --experimental-modules --experimental-json-modules src/server/server.mjs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nmotion@1.1.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\royle\AppData\Roaming\npm-cache\_logs\2021-06-06T07_31_53_439Z-debug.log
ERROR: "server" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nmotion@1.1.0 start: `run-p watch server serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nmotion@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\royle\AppData\Roaming\npm-cache\_logs\2021-06-06T07_31_53_708Z-debug.log

**Comment by ObertoIsOBS** [comment]
Same here!
